#!/bin/bash

set -eo pipefail

usage() {
    printf "Usage: git kustomize [args]

Args:
--appDir, -d   The directory that contains the applications (defaults to \"applications\").
--project, -p  The project in which the services were added to \`--appDir\`.
--env          The environment stage.
--help,    -h  Help.\n"
    exit "$1"
}

if [ "$#" -gt 0 ]; then
    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --appDir|-d) shift; APPDIR="$1" ;;
            --project|-p) shift; PROJECT="$1" ;;
            --env) shift; ENV="$1" ;;
            --help|-h) usage 0 ;;
            *) printf "%b Unrecognized option \`%s\`.\n" "$ERROR" "$OPT"; usage 1 ;;
        esac
        shift
    done
fi

if ! git rev-parse --show-toplevel &> /dev/null
then
    echo "[ERROR] This needs to be run in a Git repository."
    exit 1
fi

ROOT="$(git rev-parse --show-toplevel)"

if [ "$ROOT" != "$(pwd)" ]
then
    echo "[ERROR] This command must be run from the toplevel of the working tree."
    exit 1
fi

if [ -z "$PROJECT" ] || [ -z "$ENV" ]
then
    echo -e "[ERROR] Both \`PROJECT\` and \`ENV\` must be set.\n"
    usage 1
fi

if ! command -v git-update-services
then
    echo "[ERROR] The binary \`git-update-services\` could not be found in your PATH."
    exit
fi

git-update-services --appDir "${APPDIR:-applications}" --root "$ROOT" --project "$PROJECT" --env "$ENV"

